spring:
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.9.42.203:8087/discovery/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.cart.service

server:
  port: 29281

cassandra:
  contactpoints: 10.9.42.203
  port: 9042
  keyspace: pois_dev

elasticsearch:
  clusterName: changhongit-dev
  host: 10.9.42.203
  port: 9300
  sniff: true
  ignore_cluster_name: false
  ping_timeout: 20s
  nodes_sampler_interval: 20s

checkToken:
  endpoint: http://10.9.42.203:8087/security/oauth/check_token?token=%s
endpoints:
  health:
    id: health
    sensitive: false
    enabled: true
productprice:
  detail:
    uri: http://10.9.42.203:8087/productprices/
order:
  addOrder:
    uri: http://10.9.42.203:8087/companies/{uuid}/orders
#uri: http://10.9.42.203:8087/companies/{uuid}/orders
---

spring:
  profiles: qa

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.28.24.32:8761/discovery/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.cart.service

server:
  port: 19282

cassandra:
  contactpoints: 172.28.24.32
  port: 9042
  keyspace: pois_qa

elasticsearch:
  clusterName: changhongit-qa
  host: 172.28.24.34
  port: 9300
  sniff: true
  ignore_cluster_name: false
  ping_timeout: 20s
  nodes_sampler_interval: 20s

checkToken:
  endpoint: http://172.28.24.32:19301/security/oauth/check_token?token=%s
endpoints:
  health:
    id: health
    sensitive: false
    enabled: true
productprice:
  detail:
    uri: http://172.28.24.32:8087/productprices/
order:
  addOrder:
    uri: http://172.28.24.32:8087/companies/{uuid}/orders