#nohup java -Xms128m -Xmx256m -jar oauth2-service.jar --server.port=19301 --service.eureka.hostname=172.28.24.32 --service.cassandra.hostname=172.28.24.32 --spring.cloud.config.uri=http://172.28.24.32:19300/config &
#eureka config
eureka:
  client:
#    serviceUrl:
#      defaultZone: ${service.eureka.defaultZone}
    registry-fetch-interval-seconds: 5
    registerWithEureka: true
    fetchRegistry: true
    # 默认为30秒 
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}
    status-page-url-path: /hi
#心跳时间，即服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 5
# 发呆时间，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 30
    preferIpAddress: true